// 所有入口文件
module.exports = exports = [
    "ecode/ecode.html",
    "faq/index.html",
    "multiscreen/index.html",
    "subject/index.html",
    "subject2/index.html",
    "feedback/feedback.html",
    "feedback/suggest.html",

    "user/agreement.html",
    "user/bind.html",
    "user/bindbyemail.html",
    "user/bindtvphone.html",
    "user/changephone.html",
    "user/findpwd.html",
    "user/gitv-agreement.html",
    "user/login.html",
    "user/modifypwd.html",
    "user/profile.html",
    "user/samsung-renew.html",
    "user/setting.html",
    "user/trial7day.html",
    "user/tv-pay.html",
    "user/tv-payresult.html",
    "user/vipactivemid.html",
    "user/vipxj.html",
    "user/generate-order.html",
	"user/bindWeChat.html",

    "vip/activation-code.html",         
    "vip/autorenew-sendvip.html",         
    "vip/gold-upgrade.html",         
    "vip/memberpackage.html",         
    "vip/memberrights.html",         
    "vip/newuser-free.html",         
    "vip/vipgift.html",
    "vote/rapvote.html",
    "vvip/agreement.html",

    "account/login.html",
	"account/coupon.html",
    "account/auto-renew-manage.html",
    "account/lottery.html",
    "account/point.html",
    "account/point-award.html",
    "account/purchase-record.html",
    "account/wechat-public.html",

    "m-account/auto-renew-manage.html",
    "m-account/point-address.html",         
    "m-account/welfare-club.html",

    "m-vip/activation-code.html",
    "m-vip/autorenew-sendvip.html",
    "m-vip/newuser-free.html",

    "m-vote/rapvote.html",

	"other/gitv-agreement.html",         
    "other/gold-vip-agreement.html",
    "other/point.html",         
    "other/report.html",         
    "other/tvpay-memberagreement.html",
];